version: '3.2'

services:

  flask_server:
    container_name: notes_server
    build: ./
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - "notes_db"
    volumes:
      - ./:/app

  notes_db:
    image: mysql
    container_name: notes_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes_db
    volumes:
      - ./db:/var/lib/mysql
